package com.ext.portlet.model.impl;

import com.ext.portlet.model.PlanSectionDefinitionListItem;

/**
 * The extended model base implementation for the PlanSectionDefinitionListItem service. Represents a row in the &quot;xcolab_PlanSectionDefinitionListItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanSectionDefinitionListItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanSectionDefinitionListItemImpl
 * @see com.ext.portlet.model.PlanSectionDefinitionListItem
 * @generated
 */
public abstract class PlanSectionDefinitionListItemBaseImpl
    extends PlanSectionDefinitionListItemModelImpl
    implements PlanSectionDefinitionListItem {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan section definition list item model instance should use the {@link PlanSectionDefinitionListItem} interface instead.
     */
}
