package com.ext.portlet.model.impl;

import com.ext.portlet.model.PlanToPlan;
import com.ext.portlet.service.PlanToPlanLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PlanToPlan service. Represents a row in the &quot;xcolab_PlanToPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanToPlanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanToPlanImpl
 * @see com.ext.portlet.model.PlanToPlan
 * @generated
 */
public abstract class PlanToPlanBaseImpl extends PlanToPlanModelImpl
    implements PlanToPlan {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a plan to plan model instance should use the {@link PlanToPlan} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            PlanToPlanLocalServiceUtil.addPlanToPlan(this);
        } else {
            PlanToPlanLocalServiceUtil.updatePlanToPlan(this);
        }
    }
}
