package com.ext.portlet.model;

import com.ext.portlet.service.persistence.PlanToPlanPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PlanToPlan service. Represents a row in the &quot;xcolab_PlanToPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.PlanToPlanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.PlanToPlanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanToPlan
 * @see com.ext.portlet.model.impl.PlanToPlanImpl
 * @see com.ext.portlet.model.impl.PlanToPlanModelImpl
 * @generated
 */
public interface PlanToPlanModel extends BaseModel<PlanToPlan> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a plan to plan model instance should use the {@link PlanToPlan} interface instead.
     */

    /**
     * Returns the primary key of this plan to plan.
     *
     * @return the primary key of this plan to plan
     */
    public PlanToPlanPK getPrimaryKey();

    /**
     * Sets the primary key of this plan to plan.
     *
     * @param primaryKey the primary key of this plan to plan
     */
    public void setPrimaryKey(PlanToPlanPK primaryKey);

    /**
     * Returns the from plan ID of this plan to plan.
     *
     * @return the from plan ID of this plan to plan
     */
    public long getFromPlanId();

    /**
     * Sets the from plan ID of this plan to plan.
     *
     * @param fromPlanId the from plan ID of this plan to plan
     */
    public void setFromPlanId(long fromPlanId);

    /**
     * Returns the to plan ID of this plan to plan.
     *
     * @return the to plan ID of this plan to plan
     */
    public long getToPlanId();

    /**
     * Sets the to plan ID of this plan to plan.
     *
     * @param toPlanId the to plan ID of this plan to plan
     */
    public void setToPlanId(long toPlanId);

    /**
     * Returns the reference count of this plan to plan.
     *
     * @return the reference count of this plan to plan
     */
    public int getReferenceCount();

    /**
     * Sets the reference count of this plan to plan.
     *
     * @param referenceCount the reference count of this plan to plan
     */
    public void setReferenceCount(int referenceCount);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(PlanToPlan planToPlan);

    public int hashCode();

    public CacheModel<PlanToPlan> toCacheModel();

    public PlanToPlan toEscapedModel();

    public String toString();

    public String toXmlString();
}
