package com.ext.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PlanSectionDefinitionListItem service. Represents a row in the &quot;xcolab_PlanSectionDefinitionListItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ext.portlet.model.impl.PlanSectionDefinitionListItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ext.portlet.model.impl.PlanSectionDefinitionListItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanSectionDefinitionListItem
 * @see com.ext.portlet.model.impl.PlanSectionDefinitionListItemImpl
 * @see com.ext.portlet.model.impl.PlanSectionDefinitionListItemModelImpl
 * @generated
 */
public interface PlanSectionDefinitionListItemModel extends BaseModel<PlanSectionDefinitionListItem> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a plan section definition list item model instance should use the {@link PlanSectionDefinitionListItem} interface instead.
     */

    /**
     * Returns the primary key of this plan section definition list item.
     *
     * @return the primary key of this plan section definition list item
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this plan section definition list item.
     *
     * @param primaryKey the primary key of this plan section definition list item
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this plan section definition list item.
     *
     * @return the ID of this plan section definition list item
     */
    public long getId();

    /**
     * Sets the ID of this plan section definition list item.
     *
     * @param id the ID of this plan section definition list item
     */
    public void setId(long id);

    /**
     * Returns the section definition ID of this plan section definition list item.
     *
     * @return the section definition ID of this plan section definition list item
     */
    public long getSectionDefinitionId();

    /**
     * Sets the section definition ID of this plan section definition list item.
     *
     * @param sectionDefinitionId the section definition ID of this plan section definition list item
     */
    public void setSectionDefinitionId(long sectionDefinitionId);

    /**
     * Returns the type of this plan section definition list item.
     *
     * @return the type of this plan section definition list item
     */
    @AutoEscape
    public String getType();

    /**
     * Sets the type of this plan section definition list item.
     *
     * @param type the type of this plan section definition list item
     */
    public void setType(String type);

    /**
     * Returns the referenced ID of this plan section definition list item.
     *
     * @return the referenced ID of this plan section definition list item
     */
    public long getReferencedId();

    /**
     * Sets the referenced ID of this plan section definition list item.
     *
     * @param referencedId the referenced ID of this plan section definition list item
     */
    public void setReferencedId(long referencedId);

    /**
     * Returns the data of this plan section definition list item.
     *
     * @return the data of this plan section definition list item
     */
    @AutoEscape
    public String getData();

    /**
     * Sets the data of this plan section definition list item.
     *
     * @param data the data of this plan section definition list item
     */
    public void setData(String data);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(
        PlanSectionDefinitionListItem planSectionDefinitionListItem);

    public int hashCode();

    public CacheModel<PlanSectionDefinitionListItem> toCacheModel();

    public PlanSectionDefinitionListItem toEscapedModel();

    public String toString();

    public String toXmlString();
}
